CREATE TABLE [dbo].[ZUSRS](
	[USRID] [nvarchar](50) NOT NULL,
	[USR_NM_AR] [nvarchar](255) NULL,
	[USR_NM_EN] [nvarchar](255) NULL,
	[PWD] [nvarchar](255) NOT NULL,
	[GRPID] [smallint] NOT NULL, --[ZGRPS]
	[RMRK] [nvarchar](255) NULL,
	[ENTEREDBY] [nvarchar](50) NULL,
	[ENTRYDATE] [datetime] NULL,
	[UPDATEDBY] [nvarchar](50) NULL,
	[UPDATEDATE] [datetime] NULL,
	
 CONSTRAINT [PK_ZUSRS] PRIMARY KEY CLUSTERED 
(
	[USRID] ASC
)
) ON [PRIMARY]

GO

CREATE TABLE [dbo].[ZGRPS](
	[GRPID] SMALLINT NOT NULL,
	[GRP_NM_AR] [nvarchar](255) NULL,
	[GRP_NM_EN] [nvarchar](255) NULL,
	[RMRK] [nvarchar](255) NULL,
	[ENTEREDBY] [nvarchar](50) NULL,
	[ENTRYDATE] [datetime] NULL,
	[UPDATEDBY] [nvarchar](50) NULL,
	[UPDATEDATE] [datetime] NULL,

 CONSTRAINT [PK_ZGRPS] PRIMARY KEY CLUSTERED 
(
	[GRPID] ASC
)
) ON [PRIMARY]

GO

CREATE TABLE [dbo].[INCIDENTS_SOURCES](
	[SRC_ID] SMALLINT NOT NULL,
	[SRC_NM_AR] [nvarchar](255) NULL,
	[SRC_NM_EN] [nvarchar](255) NULL,
	[RMRK] [nvarchar](255) NULL,
	[ENTEREDBY] [nvarchar](50) NULL,
	[ENTRYDATE] [datetime] NULL,
	[UPDATEDBY] [nvarchar](50) NULL,
	[UPDATEDATE] [datetime] NULL,

 CONSTRAINT [PK_INCIDENTS_SOURCES] PRIMARY KEY CLUSTERED 
(
	[SRC_ID] ASC
)
) ON [PRIMARY]

GO
CREATE TABLE [dbo].[INCIDENTS](
	[INC_ID] INT NOT NULL,
	[INC_DSCR_AR] [nvarchar](255) NULL,
	[INC_DSCR_EN] [nvarchar](255) NULL,
	[INC_DETAILS] [nvarchar](MAX) NULL,
	[INC_SUMMARY] [nvarchar](1000) NULL,
	[INC_LVL] SMALLINT NOT NULL, --APPCODES - 1
	[INC_SRC] SMALLINT NOT NULL, --INCIDENTS_SOURCES (AND WE MAY GET DSCR TO USER)
	[INC_DT] DATETIME NOT NULL,
	[TAGS] NVARCHAR(4000),
	[LOGGED_BY] [nvarchar](50) NULL,
	[RMRK] [nvarchar](255) NULL,
	[ENTEREDBY] [nvarchar](50) NULL,
	[ENTRYDATE] [datetime] NULL,
	[UPDATEDBY] [nvarchar](50) NULL,
	[UPDATEDATE] [datetime] NULL,
 CONSTRAINT [PK_INCIDENTS] PRIMARY KEY CLUSTERED 
(
	[INC_ID] ASC
)
) ON [PRIMARY]

GO
CREATE TABLE [dbo].[PROBLEMS](
	[PROB_ID] INT NOT NULL,
	[PROB_DSCR_AR] [nvarchar](255) NULL,
	[PROB_DSCR_EN] [nvarchar](255) NULL,
	[PROB_LVL] SMALLINT NOT NULL, --APPCODES - 2
	[INC_ID] INT NOT NULL, --INCIDENTS_SOURCES (AND WE MAY GET DSCR TO USER)
	[LST_WA_ID] SMALLINT NULL,
	[LST_WA_DT] DATETIME NULL,
	[FIN_FIX_ID] SMALLINT NULL,
	[FIN_FIX_DT] DATETIME NULL,
	[IS_KNOWN_ERROR] SMALLINT NULL, -- ‰›” «·ÃœÊ· ··√Œÿ«¡ , Ì ÕÊ· ≈·Ï Œÿ√ „⁄—Ê› , ÊÌ„ﬂ‰ «‰‘«¡ ›ÌÊ ·⁄—÷ «·„⁄—Ê›Ì‰ ›ﬁÿ
	[BECAME_KE_DT] DATETIME NULL,
	[RMRK] [nvarchar](255) NULL,
	[ENTEREDBY] [nvarchar](50) NULL,
	[ENTRYDATE] [datetime] NULL,
	[UPDATEDBY] [nvarchar](50) NULL,
	[UPDATEDATE] [datetime] NULL,
 CONSTRAINT [PK_PROBLEMS] PRIMARY KEY CLUSTERED 
(
	[PROB_ID] ASC
)
) ON [PRIMARY]

GO
CREATE VIEW KNOWN_ERRORS_PROBLEMS AS SELECT * FROM [PROBLEMS] WHERE ISNULL(IS_KNOWN_ERROR,0) = 1
GO

CREATE TABLE [dbo].[WORDAROUNDS](
	[WA_ID] INT NOT NULL,
	[WA_DSCR_AR] [nvarchar](255) NULL,
	[WA_DSCR_EN] [nvarchar](255) NULL,
	[WA_DETAILS] [nvarchar](MAX) NULL,
	[WA_SUMMARY] [nvarchar](1000) NULL,
	[PROB_ID] INT NOT NULL, 
	[WA_DT] DATETIME NOT NULL,
	[TAGS] NVARCHAR(4000),
	[WA_BY] [nvarchar](50) NULL,
	[RMRK] [nvarchar](255) NULL,
	[ENTEREDBY] [nvarchar](50) NULL,
	[ENTRYDATE] [datetime] NULL,
	[UPDATEDBY] [nvarchar](50) NULL,
	[UPDATEDATE] [datetime] NULL,
 CONSTRAINT [PK_WORDAROUNDS] PRIMARY KEY CLUSTERED 
(
	[WA_ID] ASC
)
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[FIXES](
	[FIX_ID] INT NOT NULL,
	[FIX_DSCR_AR] [nvarchar](255) NULL,
	[FIX_DSCR_EN] [nvarchar](255) NULL,
	[FIX_DETAILS] [nvarchar](MAX) NULL,
	[FIX_SUMMARY] [nvarchar](1000) NULL,
	[PROB_ID] INT NOT NULL, 
	[FIX_DT] DATETIME NOT NULL,
	[TAGS] NVARCHAR(4000),
	[FIXED_BY] [nvarchar](50) NULL,
	[RMRK] [nvarchar](255) NULL,
	[ENTEREDBY] [nvarchar](50) NULL,
	[ENTRYDATE] [datetime] NULL,
	[UPDATEDBY] [nvarchar](50) NULL,
	[UPDATEDATE] [datetime] NULL,
 CONSTRAINT [PK_FIXES] PRIMARY KEY CLUSTERED 
(
	[FIX_ID] ASC
)
) ON [PRIMARY]
GO
CREATE TABLE APPCODES
(
	[ID] INT NOT NULL,
	[SEQ] INT NOT NULL,
	[DSCR_AR] [nvarchar](255) NULL,
	[DSCR_EN] [nvarchar](255) NULL,
	[RMRK] [nvarchar](255) NULL,
	[ENTEREDBY] [nvarchar](50) NULL,
	[ENTRYDATE] [datetime] NULL,
	[UPDATEDBY] [nvarchar](50) NULL,
	[UPDATEDATE] [datetime] NULL,
 CONSTRAINT [PK_APPCODES] PRIMARY KEY CLUSTERED 
(
	ID ASC,SEQ ASC
)
)
GO
INSERT INTO APPCODES (ID,SEQ,DSCR_AR,DSCR_EN,ENTEREDBY,ENTRYDATE) VALUES(0,1,'„” ÊÏ «·ÕœÀ', 'INCIDENT LEVEL','SYS',GETDATE())
GO
INSERT INTO APPCODES (ID,SEQ,DSCR_AR,DSCR_EN,ENTEREDBY,ENTRYDATE) VALUES(1,1,'„⁄·Ê„« ', 'Information','SYS',GETDATE())
GO
INSERT INTO APPCODES (ID,SEQ,DSCR_AR,DSCR_EN,ENTEREDBY,ENTRYDATE) VALUES(1,2,' Õ–Ì—', 'Warning','SYS',GETDATE())
GO
INSERT INTO APPCODES (ID,SEQ,DSCR_AR,DSCR_EN,ENTEREDBY,ENTRYDATE) VALUES(1,4,'Œÿ√', 'Error','SYS',GETDATE())
GO
INSERT INTO APPCODES (ID,SEQ,DSCR_AR,DSCR_EN,ENTEREDBY,ENTRYDATE) VALUES(0,2,'„” ÊÏ «·„‘ﬂ·…', 'Problem LEVEL','SYS',GETDATE())
GO
INSERT INTO APPCODES (ID,SEQ,DSCR_AR,DSCR_EN,ENTEREDBY,ENTRYDATE) VALUES(2,1, '⁄«œÌ…','Normal','SYS',GETDATE())
GO
INSERT INTO APPCODES (ID,SEQ,DSCR_AR,DSCR_EN,ENTEREDBY,ENTRYDATE) VALUES(2,2 , 'Â«„…','Mahor','SYS',GETDATE())
GO
INSERT INTO APPCODES (ID,SEQ,DSCR_AR,DSCR_EN,ENTEREDBY,ENTRYDATE) VALUES(2,3, '⁄«Ã·…','Critical','SYS',GETDATE())
GO
INSERT INTO APPCODES (ID,SEQ,DSCR_AR,DSCR_EN,ENTEREDBY,ENTRYDATE) VALUES(2,4, '«·⁄„· „ Êﬁ›','Blocker','SYS',GETDATE())
GO